### ISSUE TITLE
test_spike_train_generation.py uses the PyNNIO class to load test data 

### ISSUE THREAD

**Issue by pietroquaglio** [NeuralEnsemble/elephant#177]
In `test_spike_train_generation.py` in order to test the spike_extraction function, some reference artificial data, generated with `make_spike_extraction_test_data.py` and stored in a .npz file as a neo block, are loaded using the PyNNIO class which does not exist any longer. This makes fail the test.

**Comment by alperyeg** [comment]
@rgerkin did you provide the file and data? We have a working solution for it see [here](https://github.com/INM-6/elephant/commit/c037f6c163d3e4171969caa648e05e1d1c693713), using instead the `.npz` a `.txt` file and loading the analogsignal from there. Would you be fine with that solution? Because atm. we do not know any other way to load the data without the `PyNNIO`.

**Comment by alperyeg** [comment]
@pietroquaglio I think you can submit the PR. Then we can continue the discussion over there.

**Comment by alperyeg** [comment]
Fixed by #180
