### ISSUE TITLE
[Feature] Fixed version of fim.so

### ISSUE THREAD

**Issue by mdenker** [NeuralEnsemble/elephant#276]
**Feature**
Provide a fixed version of `fim.so` for each version of Elephant.

**Motivation**
Currently, `fim.so` (or the Windows equivalent) is downloaded on install-time of Elephant. This, however, leads to a situation, where different versions of fim.so are installed with the same version of Elephant. This causes a problem for package managers, when building distributions, since the hashes will change depending on when Elephant is installed.

**Comment by dizcza** [comment]
I wrote an email to Christian Borgelt, asking for versioning, a week ago. No answer yet. But I think he uses the latest version 6.28 (2017.03.24). That means the issue original author described has nothing to do with the fim.so version. I suggest you contact the man at CodeJam10 who complained about the inconsistent hashes and give him the link to this issue so that we can work through. Otherwise, I don't see the issue here.

**Comment by dizcza** [comment]
I just talked to the author of the issue and he said they don't experience the issue anymore because now they hash downloaded files (fim.so) separately and it does not break their build process anymore. Closing as not relevant (though not resolved).

The author also suggested to take a look how numpy builds cpp files, if any, on fly with pip install.
