### ISSUE TITLE
Fano factor should check that the spiketrains in the passed list are of the same duration

### ISSUE THREAD

**Issue by Qkley** [NeuralEnsemble/elephant#336]
Currently, Fano factor takes the length of each spike train in the spike train list to perform the computation. The only check that is performed is that the number of spikes in each spike train is not equal to zero. In the case of spike trains that are not even in their duration, suggesting trials of varying durations, the current method would return Fano factor value that could be rather meaningless. Therefore, it might be beneficial to perform a check or raise an error in such a case.

**Comment by dizcza** [comment]
In many cases, t_start and t_stop of spike trains (and their difference) are not aligned. Raising an error each time? - I'm not sure. Would it make sense to normalize the Fano factor by the spike train duration? Or any other technique that would make the Fano factor meaningful when the spike trains have different durations?

**Comment by Qkley** [comment]
Off the top of my head, I could see two potential solutions. Fano factor computation could be preceded by `spiketrain.time_slice()` to ensure equal durations (i.e. `t_stop = t_start + duration`). Alternatively, binning would ensure it too.

**Comment by mdenker** [comment]
The automatic method of slicing spike trains seems too much magic to me, and could lead to unexpected results. Testing the duration, however, would be a very good thing, although a warning would be better than throwing an error, preferrably something like this `Warning: Fano factor calculated for spike trains of different duration (minimum: 5.0s, maximum 5.5s).` The reason is that this way, the experimenter can judge if this is fine/tolerable for his/her workflow, or if he must use a `time_slice` statement beforehand.
