### ISSUE TITLE
[Bug] instantaneous_rate estimated rates appear shifted by one time step

### ISSUE THREAD

**Issue by gyyang** [NeuralEnsemble/elephant#360]
Rate returned by the instantaneous_rate function appear to be (incorrectly) shifted by one time step.

**To Reproduce**
```
import numpy as np
from neo.core import SpikeTrain
from quantities import s, ms
from elephant.kernels import GaussianKernel
from elephant.statistics import instantaneous_rate
spiketrain = SpikeTrain(np.array([-0.0001, 0, 0.0001])*s, t_start=-1, t_stop=1.0)
rate = instantaneous_rate(spiketrain, sampling_period=20*ms, kernel=GaussianKernel(50*ms))
print(rate.times[np.argmax(rate)])
```
**Expected behavior**
Since the 3 spikes are centered around 0, I would expect the estimated rate to peak at t=0. However, the rate returned peak at -1 * sample_period.

**Environment**
 - OS (e.g., Linux): macOS
 - How you installed elephant (`conda`, `pip`, source): pip
 - Python version: 3.7
 - `neo` python package version: 0.8.0
 - `elephant` python package version: 0.8.0

**Comment by dizcza** [comment]
Dear Guangyu Robert,
if you plot the outcome rate, you'll notice that the peak is squeed to the left due to the insufficient sampling rate. The solution is to increase the sampling rate (decrease the sampling period). Then the resulting instantaneous rate profile looks smooth and the peak is indeed centered at the origin.
Rerun your script with `sampling_period=2 * ms` and make sure that it's centered at t=0.
In general, for large values of `sample_period`, the peak can be shifted to +/- one `sampling_period` because this value defines the resolution of your output signal.

**Comment by gyyang** [comment]
Dear Danylo,

Thank you for your prompt reply. I agree with you that a lower ```sampling period``` can fix this problem. But isn't this still a bug? It would be difficult for the users to determine what is the appropriate sampling period. I have provided a code sample below, where times is centered at 0, and there's only a single spike at 0.

```
import numpy as np
from neo.core import SpikeTrain
from quantities import s, ms
from elephant.kernels import GaussianKernel
from elephant.statistics import instantaneous_rate
import matplotlib.pyplot as plt
# periods = np.arange(1, 100)
periods = [2**c for c in range(-3, 6)]
shifts = list()
for period in periods:
    spiketrain = SpikeTrain(np.array([0])*s, t_start=-period*10*ms, t_stop=period*10*ms)
    rate = instantaneous_rate(spiketrain, sampling_period=period*ms, kernel=GaussianKernel(50*ms))
    shifts.append(rate.times[np.argmax(rate)].rescale(ms)/ms/period)
plt.plot(periods, shifts)
plt.xlabel('Sampling period (ms)')
plt.ylabel('Center shift')
plt.title('Kernel with 50 ms')
```

**Comment by dizcza** [comment]
I see what you mean now: for specific of `sampling_peroid`s, the instantaneous rate timings are shifted by 1 `sampling_period` to the **right** -> the origin of a rate profile is shifted by 1 `sampling_period` to the right -> `rate.times[np.argmax(rate)]` points to the "wrong" time equals `-1*sampling_period`.
I put "wrong" in quotes because fixing this implies changing the logic and what we assumed to be "right" previously.
Thank you for pinpointing this. We'll have a closer look.

**Comment by gyyang** [comment]
Dear Danylo,

I'm not sure what's the reason for this shift, but my guess is that this happens when the ```kernel.sigma``` is not an integer multiple of the ```sampling_period```. May have something to do with this code

```
    t_arr = np.arange(-cutoff * kernel.sigma.rescale(units).magnitude,
                      cutoff * kernel.sigma.rescale(units).magnitude +
                      sampling_period.rescale(units).magnitude,
                      sampling_period.rescale(units).magnitude) * units
```
