### ISSUE TITLE
Spike Train Dissimilarity - Question

### ISSUE THREAD

**Issue by GuillaumeGirier** [NeuralEnsemble/elephant#365]
Hello everyone,

First, thank you for this package which is very useful!

I have an issue about the calculation of Victor Purpura Distance and Van Rossum Distance; let me explain my case (I read issues on your github but I didn't find an answer):

I have a matrix where I stock my spike trains under this form : 

`np.shape(Data) = ((Number of spike trains, time value of spikes))`

So, for instance, ((100,20)).

I want the distance between these 100 spike trains, where I have 20 values of time when occurs spikes.
Of course, I use the "neo" package on it, and at the end, I have a matrix like this : 

`Data`= ((Number of spike train, time value of spikes)) * ms. `

Then, I put directly my Data in the code line for VP or VR distance : 

`VPD = victor_purpura_distance(Data, 1/tau, kernel=None, sort=False, algorithm='fast')`

Where tau is time scale value created thanks to the "Quantities" package : 

`tau = [0.001 * pq.ms, 0.01 * pq.ms, 1.0 * pq.ms, 5.0 * pq.ms, 10.0 * pq.ms,  20.0 * pq.ms, 50.0 * pq.ms]`

I studied a large field of values for tau and my problem is that the values of the output distance matrix are completly false. (Because something I did wrong, I guess.)
In fact, it is an exercise where I have to compare these results with the results that my teacher has, thanks to a Matlab package.

I really would like to understand why what I did is wrong. I guess that I forget to take something in consideration...

Thank you for your answers,

Respectfully,

GIRIER Guillaume.

**Comment by mdenker** [comment]
Dear Guillaume,

thanks for contacting us. I assume the main source of error is that SpikeTrain objects in Neo only hold one spike train. The reason is that in general, multiple spike trains will have different numbers of spikes (unlike your example where all have 20 spikes), and therefore a matrix representation is not possible. Instead, we typically resort to a list of spike train objects. The following code should be adaptable to your situation:

```python
sts = []
# 100 random spike trains of 20 spikes each (could just as well be different numbers of spike per neuron, thoughl)
for i in range(100):
    sts.append(neo.SpikeTrain(np.sort(np.random.rand(20))*1000*pq.ms, t_start=0*pq.ms, t_stop= 1000*pq.ms))
# for tau = 50 ms
VPD = elephant.spike_train_dissimilarity.victor_purpura_dist(sts, 1/tau[-1], kernel=None, sort=False, algorithm='fast')
print(VPD)
```

Hope that solves your issue.

Best,
Michael

**Comment by GuillaumeGirier** [comment]
Hello,

Thank you for your answer!

If I understand well, each value has to be a neo object?

Because, as you can see here, I have a matrix where there is 100 neo sub-matrice objects:
![image](https://user-images.githubusercontent.com/55884546/97027589-3c21fe00-155b-11eb-9c5c-60c017cd7c65.png)

And I have the impression that your code does the same thing. (Or maybe I am wrong?)

Thank you again,

GIRIER Guillaume.

**Comment by mdenker** [comment]
Yes, the input must be a `list` of spike trains, so in fact that code you have posted looks correct. Let me look into this...

**Comment by GuillaumeGirier** [comment]
Hello again,

This is my code: 

`import quantities as pq
import numpy as np
from elephant.spike_train_dissimilarity import van_rossum_distance
from elephant.spike_train_dissimilarity import victor_purpura_distance
from neo.core import SpikeTrain
from random import *

def Create_ST_Reg (n, T_PLT, dt, sep_time):
    
    """
    
    Function Purpose : 
        
        The function give a list of time array of each AP.
    
    Arguments:
        
        n : record number
        T_PLT : Simulation time list.
        dt
        sep_time : numbers of spikes
        
    Return:
        
        Time : AP list for the studied neuron. Lenght of the T_PLT.
        
    """
    
    Time = []
    
    Cut = len(T_PLT)/sep_time
    Shift = int(uniform(0, int(Cut)))
    
    for n_cell in range(n) :
              
        pa_entree = np.zeros(len(T_PLT))
        
        for sep in range(sep_time):
            
            while Cut*(sep_time-1)+Shift >= len(T_PLT):
                Shift = int(uniform(0, int(Cut)))
                
            pa_entree[int(Cut*sep+Shift)] = 1
        
        Shift = int(uniform(0, int(Cut)))    
        
        Sub_Time = np.where(pa_entree > 0 ) * dt
        
        Sub_Time = np.reshape(Sub_Time, len(Sub_Time[0]))
                        
        Time.append(SpikeTrain(Sub_Time, units='ms', t_start= 0 * pq.ms, t_stop= len(T_PLT) * pq.ms))
        
    print(Time)
           
    return Time

dt = 1                                   # ms
T = 100                                  # ms, Total simulation time
T_PLT   = np.arange(0,T,dt)              # ms, tableau des temps en lesquels sont calculées les variables

n = 100                                   # Number of records

sep_time = 5

Times = Create_ST_Reg (n, T_PLT, dt, sep_time)

tau = 0.001 * pq.ms

VPD = victor_purpura_distance(Times, 1/tau, kernel=None, sort=False, algorithm='fast')

print(VPD)
`

Thank you again,

Guillaume.

**Comment by mdenker** [comment]
Cool, thanks. I'll have a look and get back to you.

**Comment by GuillaumeGirier** [comment]
Alright, I am in a hurry to have your comments on it!
Thank you.

**Comment by mdenker** [comment]
Let me try to better understand. So, running the code with `tau=10ms` 
```python
print(Times[0])
print(Times[1])
print(Times[2])
print(Times[3])
print(VPD[0:4,0:4])
```
I get
```
[17 37 57 77 97] ms
[ 9 29 49 69 89] ms
[11 31 51 71 91] ms
[14 34 54 74 94] ms

[[0.  4.  3.  1.5]
 [4.  0.  1.  2.5]
 [3.  1.  0.  1.5]
 [1.5 2.5 1.5 0. ]]
```
This seems to me at least plausible/consistent (e.g., spike trains 2 and 3 are close (VPD=1.5), and spike trains 0 and 1 are very far (VPD=4)). 

For tau=0.0001ms, I think the kernel is just too small, this results in non-sense, indeed.

So, the problem is that the numbers are too high or too low, or not consistent??

**Comment by GuillaumeGirier** [comment]
This is for example, for the same parameters (n = 100, t = 100 ms, len(time_spikes) = 5 spikes), what get my teacher with Matlab:
![image](https://user-images.githubusercontent.com/55884546/97033053-03862280-1563-11eb-8afb-4120f63f135d.png)
(It is only a part of the complete matrix.)
The values have more number after the comma and it is more various...

Guillaume.

**Comment by mdenker** [comment]
This seems to me that the implementations of the two algorithms differ. To my understanding, the VPD as a plain value is not that telling, since it is a convoluted mixture of deletions, insertions and moves -- and tau. Most important would be that in your example, where it's only about moving spikes, the VPD values behave distance-ish, i.e., more moving, more distance (like in the example above: spike train 0 is 3 ms apart from spike train 2, and 6 ms apart from spike train 3, hence the distances are 1.5 and 2*1.5=3, respectively). I guess you'll observe the same logic in the results of the matlab code.

Regarding the precise values of the VPD, these will be affected by the implementation details, and should not be compared across implementations for now. Of course, it would be great to confirm they match precisely with reference implementations of the original publications. I'll take your question as point of investigation to re-check this for Elephant, however, that will not be solved tonight :-D.

Regarding small `tau`: In this case I assume that it's cheaper to insert and delete spikes rather than moving them, therefore, Elephant gives you 10 (5 spikes inserted, 5 deleted, each at a cost of 1). For 10 spikes/spiketrain, you'll get 20's in the matrix.

**Comment by GuillaumeGirier** [comment]
Hello,

Thank you for your answer!
I will try to find a solution too.

Have a good day!
