### ISSUE TITLE
Best strategy to run Spade on desktop computer

### ISSUE THREAD

**Issue by chanokin** [NeuralEnsemble/elephant#555]
I'm trying to detect spatio-temporal patterns in my data but memory just blows up. I don't think the data is particularly large (~300 neurons firing at ~1Hz in a 3 second interval) and my computer has 256GB but, still, I can't manage to analyse the spikes because 'spade' just consumes all resources. 

I've also noticed that the `min_neu` argument seems to go unnoticed by the tool, I wanted to get patterns with more than X neurons in them but, for some reason, it doesn't work that way.

Finally, if you're interested in doing a GPU version of the thing, I could help with that but I really need a good explanation of how the thing works first.

**Comment by Moritz-Alexander-Kern** [comment]
Hey @chanokin ,
thanks for reaching out to us.

For the SPADE method there is a pure Python implementation and one using a C++ implementation of the  fp-growth algorithm.

Do you happen to know which version you are running?

You can check by trying to import the `fim` module with:

```python
from elephant.spade_src import fim
```

In a similar way: are you using MPI ?

You can check with:

```python
from mpi4py import MPI
```

Regarding the `min_neu` argument: allow me some time to look into this.

A GPU version would be a very nice feature, thanks for the kind offer, I will definitely come back to this :100: .

**Comment by chanokin** [comment]
Hey, sorry for the late reply. Here's what I've found out. 

I am running the C++ backend for fpgrowth but, I was not using MPI, I think that was the key problem as similar situations don't hoard as much memory any more. I'll keep trying new scenarios to see if I get the issue again.

**Comment by pbouss** [comment]
Hey @chanokin, 
It's great that your using SPADE to analyze your data. 
In order to reduce memory load, the `min_occ` parameter is crucial. Which is the minimal number of occurrences of a pattern so that it is stored in memory. If this parameter is too small, memory just blows up, because too many patterns are found. 
Further, if you want to restrict that the pattern has at least a certain size you can use the `min_spikes` parameter, instead of the `min_neu` parameter. For the latter one, it only gets involved when you also do a significance analysis.
For a GPU implementation that would of course be very nice. In principle, the method got already pretty fast with the new C++ core as published here: https://www.frontiersin.org/articles/10.3389/fninf.2021.723406/full .
For further insights in how we use SPADE you can also check out the code repo of our last paper: https://github.com/INM-6/SPADE_surrogates.

I hope this helps. I would be interested to hear which patterns you find in your data.

**Comment by Moritz-Alexander-Kern** [comment]
The bug related to the `min_neu` parameter was fixed here: https://github.com/NeuralEnsemble/elephant/pull/575 . 
Thanks @pbouss for fixing this.

I assume all questions regarding this matter have been answered, if not: feel free to reopen at any time.
