### ISSUE TITLE
Correcting rounding errors by shifting the affected spikes into the following

### ISSUE THREAD

**Issue by ybernaerts** [NeuralEnsemble/elephant#638]
Hi team!

I'm running GPFA models and it seems that `round_binning_errors()` in `gpfa_utils.py` is called for every spike train in each trial. This causes a long long sequence of warnings that spikes have been shifted in the next bin, due to machine precision errors. I have not found a satisfying working solution around it (e.g. by playing with the tolerance argument).

But wouldn't it be more proper to use `round()` instead of `int() `to correctly assign bin numbers here? In that case, we wouldn't need to worry bin number 6.999994 (float) would be converted to int(6.999994)=6 e.g. but would stay bin id 7 as a proper integer. Warning messages would be redundant.

Am I missing something here?

**Comment by Moritz-Alexander-Kern** [comment]
Hi @ybernaerts ,
thank you for reaching out to us.

You are correct that currently it is not possible to pass the tolerance as a parameter to the GPFA class, and this could indeed be improved in the future.

The `round_binning_errors()` function in `elephant.utils` is designed to handle binning of spike times in a way that corrects for small numerical errors that can occur due to floating-point precision issues. These small errors can result in spike times being incorrectly assigned to bins.

See also: https://elephant.readthedocs.io/en/v1.1.0/reference/_toctree/utils/elephant.utils.round_binning_errors.html

Consider the following example:

```python
from elephant.utils import round_binning_errors
round_binning_errors(0.999999, tolerance=None)
0
```
When no tolerance is provided, the function defaults to strict rounding behavior. The input value 0.999999 is very close to 1, but without a specified tolerance, the function might still round it down to 0 because it strictly follows floating-point representation without correcting for small errors.
```python
round_binning_errors(0.999999, tolerance=1e-6)
1
```
Here, the tolerance is set to 1e-6. This means the function will consider values within 1e-6 of an integer to be close enough to round to that integer. Since 0.999999 is within 1e-6 of 1, it is rounded up to 1.
```python
round_binning_errors(0.999999, tolerance=1e-7)
0
```
In this case, the tolerance is tighter, set to 1e-7. The input value 0.999999 is not within 1e-7 of 1 (it's actually 1e-6 away), so the function rounds it down to 0.

Does this answer your question?

**Comment by ybernaerts** [comment]
Hi @Moritz-Alexander-Kern ,

thank you for getting back to me.

I understand how the function works and thus why certain spikes need to be shifted. The issue here is more related to the fact that, the warning message "Correcting rounding errors by shifting the affected spikes into the following bin" will be thrown numerous times as this could be the case for various spiketrains in different trials and that I don't think it is needed.

Perhaps this could indeed be resolved with passing the tolerance parameter in GPFA, not sure.

Best,
Yves

**Comment by Moritz-Alexander-Kern** [comment]
Hey @ybernaerts ,

Sorry I didn't understand you are mainly concerned with the frequent warning messages. 

In this case adjusting the log level to "ERROR" will simply suppress these warnings:
```python
from elephant.utils import logger
logger.setLevel('ERROR')
```

**Comment by Moritz-Alexander-Kern** [comment]
In this case, this issue is the same as: https://github.com/NeuralEnsemble/elephant/issues/567 ?

**Comment by ybernaerts** [comment]
Hi @Moritz-Alexander-Kern , apologies that I didn't see that exact same issue already being addressed.
I agree there that maybe suppressing all user warnings is not desired, but for now it's a workaround.
Feel free to close this issue.
thank you for the replies

Yves

**Comment by Moritz-Alexander-Kern** [comment]
Hey Yves
No worries, you are welcome :+1: 
Best Moritz
